version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 30s
      timeout: 30s
      retries: 5
    ports:
      - "5672:5672" # RabbitMQ
      - "15672:15672" # Management interface
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend
      
  receiver:
    build: ./receiver
    restart: always
    # depends_on:
    #   - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - backend
    # healthcheck:
    #   test: ["CMD-SHELL", "nc -z localhost 5672 || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    # logging:
    #   driver: json-file
    #   options:
    #     max-size: "10m"
    #     max-file: "3"

  producer:
    build: ./sender
    restart: always
    volumes:
      - ./image:/usr/src/app/image 
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - backend

volumes:
  rabbitmq_data:
  #video_data

networks:
  backend: